name: pages
on: [push]
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 12
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter pub get
      - name: Build
        run: |
          cd example
          flutter create --platforms web .
          flutter build web --base-href /cross_file_image/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: example/build/web
