name: release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
jobs:
  release:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build
        run: |
          cd example
          flutter create . --platforms web
          flutter build web --web-renderer canvaskit --base-href /cross_file_image/
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: example/build/web
      - name: Update
        run: |
          export version=$(echo ${{ github.ref_name }} | sed s/v//)
          sed -i -r "s/version: .*/version: $version/" pubspec.yaml
          git tag --format=$'## %(refname:short)\n%(subject)\n' --sort=-v:refname > CHANGELOG.md
      - uses: dart-lang/setup-dart@v1
      - run: dart pub publish -f
